# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUIMain.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Main(object):
    def setupUi(self, Main):
        Main.setObjectName("Main")
        Main.resize(497, 540)
        Main.setMinimumSize(QtCore.QSize(497, 540))
        Main.setMaximumSize(QtCore.QSize(497, 540))
        Main.setProperty("Area_Per", "")
        self.centralwidget = QtWidgets.QWidget(Main)
        self.centralwidget.setObjectName("centralwidget")
        self.labelSelect = QtWidgets.QLabel(self.centralwidget)
        self.labelSelect.setGeometry(QtCore.QRect(20, 30, 461, 71))
        font = QtGui.QFont()
        font.setFamily("American Typewriter")
        font.setPointSize(36)
        font.setItalic(False)
        self.labelSelect.setFont(font)
        self.labelSelect.setStyleSheet("font: 36pt \"American Typewriter\";\n"
"color:rgb(15, 128, 255)")
        self.labelSelect.setTextFormat(QtCore.Qt.PlainText)
        self.labelSelect.setScaledContents(True)
        self.labelSelect.setAlignment(QtCore.Qt.AlignCenter)
        self.labelSelect.setWordWrap(True)
        self.labelSelect.setObjectName("labelSelect")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setEnabled(True)
        self.line.setGeometry(QtCore.QRect(7, 100, 481, 20))
        self.line.setStyleSheet("color:rgb(179, 179, 179)")
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(10, 10, 481, 20))
        self.line_2.setStyleSheet("color:rgb(179, 179, 179)")
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.labelShape = QtWidgets.QLabel(self.centralwidget)
        self.labelShape.setGeometry(QtCore.QRect(20, 130, 461, 51))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(18)
        self.labelShape.setFont(font)
        self.labelShape.setAlignment(QtCore.Qt.AlignCenter)
        self.labelShape.setObjectName("labelShape")
        self.buttonCircle = QtWidgets.QPushButton(self.centralwidget)
        self.buttonCircle.setGeometry(QtCore.QRect(40, 210, 191, 91))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(24)
        self.buttonCircle.setFont(font)
        self.buttonCircle.setStyleSheet("font: 24pt \"Georgia\";\n"
"color:rgb(15, 128, 255)")
        self.buttonCircle.setObjectName("buttonCircle")
        self.buttonRectangle = QtWidgets.QPushButton(self.centralwidget)
        self.buttonRectangle.setGeometry(QtCore.QRect(260, 210, 191, 91))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(24)
        self.buttonRectangle.setFont(font)
        self.buttonRectangle.setStyleSheet("font: 24pt \"Georgia\";\n"
"color:rgb(15, 128, 255)")
        self.buttonRectangle.setObjectName("buttonRectangle")
        self.buttonTriangle = QtWidgets.QPushButton(self.centralwidget)
        self.buttonTriangle.setGeometry(QtCore.QRect(260, 340, 191, 91))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(24)
        self.buttonTriangle.setFont(font)
        self.buttonTriangle.setStyleSheet("font: 24pt \"Georgia\";\n"
"color:rgb(15, 128, 255)")
        self.buttonTriangle.setObjectName("buttonTriangle")
        self.buttonSquare = QtWidgets.QPushButton(self.centralwidget)
        self.buttonSquare.setGeometry(QtCore.QRect(40, 340, 191, 91))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(24)
        self.buttonSquare.setFont(font)
        self.buttonSquare.setStyleSheet("font: 24pt \"Georgia\";\n"
"color:rgb(15, 128, 255)")
        self.buttonSquare.setObjectName("buttonSquare")
        Main.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Main)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 497, 24))
        self.menubar.setObjectName("menubar")
        Main.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Main)
        self.statusbar.setObjectName("statusbar")
        Main.setStatusBar(self.statusbar)

        self.retranslateUi(Main)
        QtCore.QMetaObject.connectSlotsByName(Main)

    def retranslateUi(self, Main):
        _translate = QtCore.QCoreApplication.translate
        Main.setWindowTitle(_translate("Main", "Area & Perimeter Shape Calculator"))
        self.labelSelect.setText(_translate("Main", "AREA  &  PERIMETER  SHAPE CALCULATOR"))
        self.labelShape.setText(_translate("Main", "CHOOSE YOUR SHAPE"))
        self.buttonCircle.setText(_translate("Main", "CIRCLE"))
        self.buttonRectangle.setText(_translate("Main", "RECTANGLE"))
        self.buttonTriangle.setText(_translate("Main", "TRIANGLE"))
        self.buttonSquare.setText(_translate("Main", "SQUARE"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Main = QtWidgets.QMainWindow()
    ui = Ui_Main()
    ui.setupUi(Main)
    Main.show()
    sys.exit(app.exec_())
